Update demo-workflow.yml

diff --git a/.github/workflows/demo-workflow.yml b/.github/workflows/demo-workflow.yml
--- a/.github/workflows/demo-workflow.yml
+++ b/.github/workflows/demo-workflow.yml
@@ -8,9 +8,10 @@ on:
         required: true
 
 env:
+  RELEASE_VERSION: ${{ github.event.inputs.version }}
   TAG: v${{ github.event.inputs.version }}
   JAR_NAME: format('deezer-api-{0}-jar-with-dependencies.jar', ${{ github.event.inputs.version }})
-  JAR_PATH: target/${{ env.JAR_NAME }}
+  JAR_PATH: target/JAR_NAME
 
 jobs:
   run-demo:
@@ -19,3 +20,4 @@ jobs:
       - run: |
           echo "JAR_NAME=${{ JAR_NAME }}"
           echo "JAR_PATH=${{ JAR_PATH }}"
+          echo [[ $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alfa|-beta)$ ]] || echo "::error::Incorrect release version: $RELEASE_VERSION." && exit 1
