Update demo-workflow.yml

diff --git a/.github/workflows/demo-workflow.yml b/.github/workflows/demo-workflow.yml
--- a/.github/workflows/demo-workflow.yml
+++ b/.github/workflows/demo-workflow.yml
@@ -19,4 +19,4 @@ jobs:
       - run: |
           echo "JAR_NAME=${{ env.JAR_NAME }}"
           echo "JAR_PATH=${{ env.JAR_PATH }}"
-          echo [[ $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-alfa|-beta)$ ]] || echo "::error::Incorrect release version: $RELEASE_VERSION." && exit 1
+          (echo "1.0.0" | grep -Eq ^[0-9]+\.[0-9]+\.[0-9]+\(-alfa\|-beta\)?$) || echo "::error::Incorrect release version: $RELEASE_VERSION." && exit 1
